---
title: "免疫共沉淀（Co-immunoprecipitation，Co-IP）"
date-modified: today
categories: [protocols, immune]
---

免疫沉淀：用固定在磁珠上的特定抗体（固相化抗体），从复杂的混合物中，纯化单一抗原的实验。

已知抗原称为诱饵蛋白，与之结合的蛋白质或配体称为靶蛋白

在免疫共沉淀实验中，加入诱饵蛋白的特异性抗体，该抗体与诱饵蛋白结合使诱饵蛋白沉淀，同时细胞内与诱饵蛋白相互作用结合在一起的其他蛋白也会沉淀下来。

当复合物中涉及的蛋白质彼此紧密结合时，这种方法就会起作用，从而可以通过用抗体锁定一个成员来将复合物的多个成员从溶液中拉出。这种将蛋白质复合物从溶液中拉出的概念有时被称为“pull-down”。Co-IP 是一种强大的技术，分子生物学家经常使用它来分析[蛋白质-蛋白质相互作用](https://en.wikipedia.org/wiki/Protein%E2%80%93protein_interaction "Protein–protein interaction")。

## [免疫共沉淀]{style="color:red"}co-immunoprecipitation (Co-IP)

## 仪器与试剂

1.  Co-Ip裂解液

## 方法与步骤

1.  细胞密度达到80%左右收集细胞到15mL离心管中国，以1000r/min离心5min

2.  弃去上清，用预冷的PBS悬浮沉淀，1000r/min离心5min，重复2次

3.  弃去上清，加入RIPA细胞裂解液（+蛋白酶抑制剂）悬浮细胞沉淀

4.  离心管放在混匀仪上4℃孵育15min （hh:mm\~hh:mm）

5.  以14000r/min，4℃ 离心30min

6.  以10000r/min 离心30min，上清转移至新的Eppendorf管中

7.  枪头前端剪掉2mm，取适量的蛋白A/G树脂，用预冷的PBS悬浮，1000r/min，4℃离心1 min，弃去上清。重复2次

8.  加入适量PBS，蛋白A/G树脂/PBS 50%悬浆液

9.  蛋白定量

10. 将适量抗体加入第6步的细胞裂解液，混匀仪4℃ 2h 或过夜

11. 加入第8步的蛋白A/G树脂/PBS 50%悬浆液，混匀仪4℃ 2h 或过夜

12. 以14000r/min，4℃ 离心5s，上清转移至新的Eppendorf管中

13. 上样

14. 电泳
