---
title: "蛋白质印迹（Western Blotting，WB）"
date-modified: today
categories: [protocols, immune]
---

蛋白质免疫印迹（protein immunoblotting）

## <mark>试剂和仪器</mark>

### 试剂

1.  PBS
2.  高效RIPA裂解液
3.  WB及Co-Ip裂解液
4.  <mark>BCA法：A液，B液</mark>
5.  5 × loading buffer
6.  电泳缓冲液：5×，Tris；Glycine；SDS
7.  转膜缓冲液：700ml $ddH_2O$ ： 200ml 甲醇 ：100ml 10×转膜液 4℃冰箱预冷
8.  封闭液
9.  1×TBST
10. 一抗
11. 二抗
12. 一抗稀释液
13. 二抗稀释液
14. 显影液：A液，B液

[什么是TBS、TBST、PBS、PBST缓冲液有什么区别？](https://www.gswmed.com/list_3/208)

### 仪器

1.  恒温摇床

2.  冷冻离心机 <mark>参数 转速 半径</mark>

3.  96孔酶标板

## 实验操作

[所有操作应于冰上/4℃ 进行]{style="color:red"}

1.  蛋白提取
    1.  洗涤细胞 <mark>细胞来源：动物信息、编号、性别、年龄、体重、清洁度、细胞株、基因信息</mark>
    2.  裂解
2.  蛋白定量 [样品所有人姓名，样品制备或分装年月日，全部基本信息（批号、纯度、浓度）]{style="color:red"} 例如：<mark>AlexFluoro647-G3-(GfO)9,365 uM in ddH2O by UV\@647nm,95%(MALDI),LY,2021.07.21</mark>
    1.  96孔板
    2.  BCA，稀释10倍
    3.  恒温37℃孵育30min 具体：<mark>恒温孵育 9日11:34至12:05</mark>
    4.  酶标仪，ABS，562nm 具体：<mark>在562nm的紫外吸收（A1+A2+A3/3=A平均 ） </mark>
    5.  计算浓度
3.  蛋白变性
    1.  protein:5×loading buffer=4:1稀释
    2.  95℃加热5分钟
    3.  若是Co-IP，利用beads说明书
4.  计算上样量
    1.  $\frac{上样量(μg)}{c×8}$
5.  电泳（低温，冰盒，电泳槽）
    1.  预制胶，撕掉底部的红色封条
    2.  电泳液，外槽用旧的达到下方刻度，内槽用的新加满至溢出
    3.  缓慢垂直向上拔出点样梳，将上样孔的气泡赶尽
    4.  10微升移液器紧贴玻璃板缓慢上样，单孔上样每次不超过20μL，总蛋白20-50μg，纯化蛋白100ng-2μg
    5.  marker
    6.  （可选）阳性对照（前期检测结果正确的多余的蛋白质），阴性对照
    7.  红对红，黑对黑，接通电源恒压100-140V，60min，内槽金属丝周围出现小气泡
6.  湿法转膜 硝酸纤维素（NC）膜和聚偏二氟乙烯（PVDF）膜
    1.  根据凝胶大小，剪切PVDF膜成适宜大小
    2.  PVDF膜活化：甲醇，膜由不透明变成均一的版透明，然后将膜放入提前配好的预冷的转膜液中平衡5min，右上角剪切一部分标记以区分方向
    3.  电泳后的凝胶用水冲洗去电泳液，再用转膜液平衡3-5min
    4.  用硬塑料片撬开一面玻璃板，切除浓缩胶，留下含有目的蛋白的凝胶
    5.  转膜夹，海绵垫，滤纸，浸没在含有转膜液的托盘中，**三明治结构**：（黑色负极）黑色面，海绵垫，滤纸，凝胶，PVDF膜，滤纸，海绵垫，白色面（红色正极），黑胶白膜
    6.  流式管滚动赶尽气泡，用白色滑块夹上转膜夹
    7.  转移夹的黑面对转移槽的黑面，转移夹的白面对转移槽的白面
    8.  转膜槽中加入转膜液至没过”三明治“，盖上安全盖，放置冰盒
    9.  红对红，黑对黑，接通电源恒流280mA，60-90min，
7.  PVDF膜放入PBS-T溶液，振荡5min×3次
8.  塑料手套，切割膜上的目的蛋白
9.  封闭
    1.  5%奶粉TBST溶液
    2.  摇床50，1h
10. 一抗孵育 特异性抗体
    1.  一抗稀释液1：1000
    2.  摇床50，4℃ .pm\~ .am,
    3.  TBST洗涤，3min×3
11. 二抗孵育 碱性磷酸酶、辣根过氧化物酶或放射性核素标记的第二抗体
    1.  二抗稀释液1：4000\~5000
    2.  摇床50，室温1h
    3.  TBST洗涤，3min×3
12. 显影
    1.  配制显影液
    2.  显影仪 <mark>电脑文件夹数据图像命名：姓名日期参数Marker/Samples</mark> 结果：具体<mark>数值/图像/现象/颜色</mark>

多用图表

| 步骤       | 2024-11-12 | 2024-11-14 | ...... | 2024-11-19 |
|------------|------------|------------|--------|------------|
| 1.动物模型 |            |            |        |            |
| 2.细胞     |            |            |        |            |
| 3.蛋白提取 |            |            |        |            |
| 4.蛋白定量 |            |            |        |            |
| ......     |            |            |        |            |

: **WB**

成功的失败的、反思总结

**重复、阴性对照**

**奇偶页法**

左边写实验设计 假设 对照 原始数据 草图 现象

右边正式步骤 数据 分析

**所有过程都务必记录**
